f = open('app/admin/page.js', 'r', encoding='utf-8')
c = f.read()
f.close()
print('count:', c.count('id:"resources"'))
idx1 = c.find('id:"resources"')
idx2 = c.find('id:"resources"', idx1+1)
out = open('sidebar.txt', 'w', encoding='utf-8')
out.write(c[idx1-20:idx1+80] + '\n---\n' + c[idx2-20:idx2+80])
out.close()
print('done')
