f = open('app/admin/page.js', 'r', encoding='utf-8')
c = f.read()
f.close()
idx = c.find('case "progress"')
idx2 = c.find('renderPage')
idx3 = c.find('page===')
out = open('sidebar.txt', 'w', encoding='utf-8')
out.write(c[idx3:idx3+400])
out.close()
print('progress:', idx, 'renderPage:', idx2, 'page===:', idx3)
