f = open('app/admin/page.js', 'r', encoding='utf-8')
c = f.read()
f.close()
print('resources router:', c.count("case 'resources'"))
idx = c.find("id:\"resources\"")
out = open('sidebar.txt', 'w', encoding='utf-8')
out.write(c[idx-20:idx+100])
out.close()
print('done')
