f = open('app/admin/page.js', 'r', encoding='utf-8')
c = f.read()
f.close()
idx = c.find('page==="progress"')
idx2 = c.find('page==="staff"')
idx3 = c.find('ProgressPage')
out = open('sidebar.txt', 'w', encoding='utf-8')
out.write(c[idx3-200:idx3+100])
out.close()
print('progress page:', idx, 'staff page:', idx2, 'ProgressPage:', idx3)
