f = open('app/student/page.js', 'r', encoding='utf-8')
c = f.read()
f.close()
idx = c.find('Study Resources')
out = open('student_res.txt', 'w', encoding='utf-8')
out.write(c[idx-100:idx+200])
out.close()
print('found at:', idx)
