f = open('app/admin/page.js', 'r', encoding='utf-8')
c = f.read()
f.close()
idx = c.find('certif')
out = open('sidebar.txt', 'w', encoding='utf-8')
out.write(c[idx-100:idx+400])
out.close()
print('done, found at:', idx)
