f = open('app/admin/page.js', 'r', encoding='utf-8')
c = f.read()
f.close()
idx = c.find('nav')
out = open('sidebar.txt', 'w', encoding='utf-8')
out.write(c[idx:idx+500])
out.close()
print('done at:', idx)
