f = open('app/admin/page.js', 'r', encoding='utf-8')
c = f.read()
f.close()
idx = c.find('Certifications')
out = open('sidebar.txt', 'w', encoding='utf-8')
out.write(c[idx-200:idx+300])
out.close()
print('done at:', idx)
