f = open('app/student/page.js', 'r', encoding='utf-8')
c = f.read()
f.close()
idx = c.find('tab==="resources"')
out = open('stu.txt', 'w', encoding='utf-8')
out.write(c[idx-100:idx+100])
out.close()
print('found at:', idx)
