f = open('app/admin/page.js', 'r', encoding='utf-8')
c = f.read()
f.close()
idx = c.find('function ProgressPage')
out = open('progress_section.txt', 'w', encoding='utf-8')
out.write(c[idx:idx+100])
out.close()
print('found at:', idx)
print('sections:', [x for x in ['Announcements','Progress','Attendance','Staff','Settings'] if x in c])
